### ISSUE TITLE
ghactivity_team shortcode: fix so it can display info for teams

### ISSUE THREAD

**Issue by jeherve** [jeherve/ghactivity#4]
https://github.com/jeherve/ghactivity/blob/master/shortcodes/team-activity.php

The shortcode does not currently work, it would need to be fixed.
We also have the opportunity to get rid of a lot of duplicate code, that already exists in https://github.com/jeherve/ghactivity/blob/master/reports.ghactivity.php

**Comment by brbrr** [comment]
Fixed in #10
